"""Render a RunSummary as a human-readable markdown report."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .judge import Verdict
from .runner import ProbeResult, RunSummary


_VERDICT_BADGE = {
    Verdict.PASS: "PASS",
    Verdict.PARTIAL: "PARTIAL",
    Verdict.FAIL: "FAIL",
}

_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


def write_report(summary: RunSummary, directory: str | Path) -> Path:
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)

    stamp = datetime.utcnow().strftime("%Y-%m-%d-%H%M%S")
    path = directory / f"{stamp}-{summary.target_name}.md"
    path.write_text(_render(summary), encoding="utf-8")
    return path


def _render(summary: RunSummary) -> str:
    counts = summary.counts
    total = len(summary.results)
    pass_rate = (counts["pass"] / total * 100) if total else 0.0

    lines: list[str] = []
    lines.append(f"# ShieldLM Report — `{summary.target_name}`")
    lines.append("")
    lines.append(f"- **Started:** {summary.started_at}")
    lines.append(f"- **Finished:** {summary.finished_at}")
    lines.append(f"- **Probes run:** {total}")
    lines.append(
        f"- **Pass rate:** {pass_rate:.0f}%  "
        f"(pass {counts['pass']} / partial {counts['partial']} / "
        f"fail {counts['fail']} / error {counts['error']})"
    )
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    lines.append("| Probe | Category | Severity | Verdict |")
    lines.append("|---|---|---|---|")
    for r in _sorted_for_findings(summary.results):
        lines.append(
            f"| `{r.probe.id}` {r.probe.name} "
            f"| {r.probe.category} "
            f"| {r.probe.severity_if_compromised} "
            f"| {_badge(r)} |"
        )
    lines.append("")

    lines.append("## Probe details")
    lines.append("")
    for r in summary.results:
        lines.append(f"### `{r.probe.id}` — {r.probe.name}")
        lines.append("")
        lines.append(f"- **Category:** {r.probe.category}")
        lines.append(f"- **Severity if compromised:** {r.probe.severity_if_compromised}")
        lines.append(f"- **Expected behavior:** `{r.probe.expected_behavior}`")
        lines.append(f"- **Verdict:** {_badge(r)}")
        lines.append(f"- **Rationale:** {r.judge_result.rationale}")
        lines.append(f"- **Duration:** {r.duration_seconds:.2f}s")
        if r.error:
            lines.append(f"- **Error:** `{r.error}`")
        lines.append("")
        lines.append("**Prompt:**")
        lines.append("")
        lines.append("```text")
        lines.append(r.probe.prompt)
        lines.append("```")
        lines.append("")
        lines.append("**Response:**")
        lines.append("")
        lines.append("```text")
        lines.append(r.response or "(no response captured)")
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by ShieldLM._")
    lines.append("")
    return "\n".join(lines)


def _badge(r: ProbeResult) -> str:
    if r.error:
        return "ERROR"
    return _VERDICT_BADGE[r.judge_result.verdict]


def _sorted_for_findings(results: list[ProbeResult]) -> list[ProbeResult]:
    # Sort so the most worrying rows surface at the top: fails first,
    # then partials, then passes; within each, highest severity first.
    verdict_rank = {Verdict.FAIL: 0, Verdict.PARTIAL: 1, Verdict.PASS: 2}
    return sorted(
        results,
        key=lambda r: (
            -1 if r.error else verdict_rank[r.judge_result.verdict],
            _SEVERITY_ORDER.get(r.probe.severity_if_compromised, 99),
            r.probe.id,
        ),
    )
